language: node_js
node_js:
- '12'
cache:
  yarn: true
  directories:
  - node_modules
before_install:
  - npm install -g yarn # make sure yarn is new
  - npm config set spin false
  - npm install -g npm@^6.9.0
script:
- yarn test-ci
- yarn build
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "JcMXfObTqMXMA7ddnqvUPGR7GtgK04Zit5WiJ3dsjcV3ryTeWZ5ebGmqFGcsu0YCBZw1tRJ+c8lRNWatFLbbI0u88BDXrhg94UR5eN/rduRec7gFTv3Ph05fd1sajbYh7yA2pQgYTBC/j+ItLWs7AWGNm5dYJ0wY8TmU1kHVuxv5dpvNy5md2EhXwq1dTwkLvdRjKqmlC9trk53bQQQdiFemrWiNet87XKuQb+C0qBAYjcuBh78r3zv4wiq15HLw4RUDRMm0cHGAP5E7iFffCi3DYJlzcmdMmZrhYwtvUwxoBKYEVPqVmv391WVMyjX2QFjYyz90HSRuoFZ7eRUXC8t0ee5c++VH9c4KYm2yAti1atdEmfrfoBItau3MarH76CboUg4+ybnpbVouztko9aEDfcnGiHzSrQr89oiupceE69vPveJfB1DwE83SIHBb3I4m5DH7q4zT3vsQAv0NPppHM51NednINDhrnMWVLfKcR4rg+j/eRas0QkuAYnkHSPzDs4tTz1TLRk+9JiZqBn41QAGe0e6mc/j773ndfIOynlRWGmhIWVkusnzvFVbHAhSltI9/Wwm5xHF3cPyLkh1vuO4jK1NE7AqPD1SleVYcV4Thyx0UqXko25Ugqj8wy1cjnwiSKjtE1dbPzj7bWtUvOw6JgMADoj+a5K9RLLE="
  file:
    - build/_output/this-or-that.wigt
    - build/_output/this-or-that-build-info.yml
  on:
    tags: true
    repo: ucfopen/this-or-that-materia-widget
notifications:
  email: false
  slack:
    secure: "pbqgHSnFFCEU1iL5Zp8Do0Pcgf23dZ5YjF0bauYAY+Wrgc85DF0m7n/s3Sdw3mTLvmF6Q4JFTqHRfuU30YGQir4QBpnfLKqZuDG11L/J5BqZ1+vKA2byjCOByKVOM1uO4MEbIF+EDsQ6MkGY1PBiatqJ8wcyC0Og/zLyy72oInaClHRRKiTKqQSssZ1ZgDAB6xa7Xb0X72YOZnaxcICuK69VCN93MQwlROq/TyAtj6IHPBnG5vvwutP5UlHBM3tW6CmQeyu8bcGLAwaObHk62Hh065cW8UIFt6L1GVPFNZ8No4J4dA+1CS99ROiRNgrRsWnT/u459SnSE6VJsU/QAw5W+3YBQpCSMMnQZSL8x/J93Qm8cCEAKsliXAOfEl7J3JY5VsxCDJ8OW7ihWwP1LFaSwdwcQTjx9xIvuyTf3x/kLse3Jhb5vQ7bH4jxLNKzlAnLFJok9ytJ+V1CfJmiJ/hcihBEQJRjRXybuk2P4heCoDqYhFCq9bIwErOGVXoXzooE2PM5FSqy1u9Y9ww3o5Qf30GBTDxazVpVCXAjYMl8agamIDWYJpBP9SqOA/wobPB5t06pcyBsZddjJdfx23QIBaahOedb51kacLZVSMycBgZDaEhw7a9W8yH9q9t9DPSNzA1wCGqwiFGonTN0t+vppUwaFlma4E7MuiShKaI="
